linters:
  stylelint:
    config: 'stylelint.config.js'
    fixer: true
files:
  ignore:
    - 'normalize.css'
    - 'bootstrap-reboot.css'
    - 'reboot.css'
    - 'reset.css'

fixers:
  enable: true